#!/bin/sh

# Tim Pope: Effortless Ctags with Git
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

# Prevent spawning lots of ctags processes during big rebases by using a directory-based lock.
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html#comment-728214764

set -e

# Don't run ctags again if it's already running
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT

ripper-tags -R -f .git/tags.$$ --tag-relative --exclude=.git --exclude=tmp --exclude=vendor
mv .git/tags.$$ .git/tags
