#!/usr/bin/env bash

# General
alias b='bundle exec'
alias c='clear'
alias d='docker'
alias g='git'
alias gr='grep -rn'
alias grep='grep -I --color'
alias grepn='grep -n'
alias grepv='grep -v'
alias ipe='ipconfig getifaddr en0'
alias ipw='ipconfig getifaddr en1'
alias ism='iex -S mix'
alias kb='keybase'
alias ls='ls -Gp'
alias n='nvim'
alias topcpu='top -n10 -ocpu'
alias y='yat.sh'

# Config Management
alias dotfiles='cd ~/.dotfiles'
alias ealias='$EDITOR ~/.dotfiles/bash/aliases'
alias ebashconf='$EDITOR ~/.dotfiles/bash/config'
alias ebashfunc='$EDITOR ~/.dotfiles/bash/functions'
alias ebashrc='$EDITOR ~/.dotfiles/bashrc'
alias ebashprof='$EDITOR ~/.dotfiles/bash_profile'
alias egitconf="$EDITOR ~/.dotfiles/gitconfig -c 'setfiletype gitconfig'"
alias eirbrc='$EDITOR ~/.dotfiles/irbrc'
alias escreenrc='$EDITOR ~/.dotfiles/screenrc'
alias evimrc='$EDITOR ~/.dotfiles/vimrc'
alias salias='. ~/.dotfiles/bash/aliases'
alias sbashconf='. ~/.dotfiles/bash/config'
alias sbashrc='. ~/.dotfiles/bashrc'
