#!/bin/sh

# Tim Pope: Effortless Ctags with Git
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
trap "rm -f .git/tags.$$" EXIT
ctags -R -f .git/tags.$$ --tag-relative --exclude=.git --languages=-javascript,sql
mv .git/tags.$$ .git/tags
