#!/bin/bash

#
# Environment
#

export EDITOR=/usr/bin/vim
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export TERM=xterm-256color

#
# Functions
#

function vg {
  if [ $# -ge 2 ]; then
    local matching_files=$(grep -rl "$@")

    if [ "$matching_files" ]; then
      vim -p +/"$1" $matching_files
    else
      echo 'No matches found.'
    fi
  else
    echo 'Usage: vg <pattern> <path> [<path>...]'
  fi
}

#
# Git
#

source ~/.git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true

# Enable completion for 'g'
complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null || complete -o default -o nospace -F _git g

#
# Prompt
#

PS1="\n\[$BLD_WHI\]\u\[$REG_RED\]@\[$REG_BLU\]\h \[$REG_CYA\]\w\[$BLD_GRE\] \$(__git_ps1 "%s")\n❯\[$DEFAULT\] "

#
# RVM (must be last)
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
